### PR TITLE
Allow special return values to shortcircuit other constraints

### PR DESCRIPTION
**Pull request by goldenapples**
Adds a specialized version of `apply_filters()`, which allows functions hooked on filters to easily short-circuit all other filters on a hook by returning special return values, which are defined as constants.

These constants are pretty self-explanatory:

* `SPEED_BUMPS_RETURN_FALSE_AND_SKIP`
* `SPEED_BUMPS_RETURN_FALSE_AND_REMOVE_ALL`
* `SPEED_BUMPS_RETURN_TRUE_AND_SKIP`
* `SPEED_BUMPS_RETURN_TRUE_AND_REMOVE_ALL`

Basically "skip" return values prevent the other constraints at the current paragraph from being run, and "remove all" values prevent constraints from the current speed bump from being run over the rest of the content.

This is a continuation of #74, but extended so that it can be used for many other contexts. Since many of the speed bump constraints are computationally expensive, its much better to be able to return false early and prevent a speed bump from being inserted, if a simple test like paragraph length or string matching can determine that the speed bump will not be inserted anywhere in the content, rather than running dozens of regexes at every paragraph through a long post.
  

This is an essential feature when running potentially expensive operations over long strings of content. If trying to process a 200-paragraph post, if we know we're only trying to insert a speed bump in the last 20% of the article, shortcircuiting all of the regex constraints over the first 160 paragraphs can be the difference between 10 seconds page generation time and .1 second.

See #75

### CODE REVIEW

**Comment by goldenapples** [comment]
I'd like to hear thoughts on this approach to improving performance here. 

@ryanboswell @danielbachhuber Does this look good?

**Comment by danielbachhuber** [comment]
I'll need to digest some before I can offer feedback on the problem itself. However, in terms of coding style, I'm not a huge fan of magic <del>numbers</del><ins>strings</ins> in constants. Seems like there should be another way.

**Comment by goldenapples** [comment]
> in terms of coding style, I'm not a huge fan of magic <del>numbers</del><ins>strings</ins> in constants. Seems like there should be another way.

Yeah, I'm sure there is. But anything I could think of to use (returning WP_Errors and handling those values specially, using magic numbers that could be coerced to booleans) seemed equally hacky. I thought the concept of using constants, and setting those to values which aren't likely to be used under any real-world circumstance, was the most approachable I could think of.

**Comment by goldenapples** [comment]
> I'm not a huge fan of magic numbers/strings in constants. Seems like there should be another way.

I've been thinking about this and still don't have a really good alternative. 

I considered some kind of bitmask-based settings:

```
define( 'SPEED_BUMPS_FALSE',                        0 );
define( 'SPEED_BUMPS_TRUE',                         1 );
define( 'SPEED_BUMPS_RETURN_AND_SKIP',              2^1 );
define( 'SPEED_BUMPS_REMOVE_ALL',                   2^2 );

define( 'SPEED_BUMPS_RETURN_FALSE_AND_SKIP',        SPEED_BUMPS_RETURN_AND_SKIP | SPEED_BUMPS_FALSE );
define( 'SPEED_BUMPS_RETURN_FALSE_AND_REMOVE_ALL',  SPEED_BUMPS_REMOVE_ALL | SPEED_BUMPS_RETURN_AND_SKIP | SPEED_BUMPS_FALSE );
define( 'SPEED_BUMPS_RETURN_TRUE_AND_SKIP',         SPEED_BUMPS_RETURN_AND_SKIP | SPEED_BUMPS_TRUE );
define( 'SPEED_BUMPS_RETURN_TRUE_AND_REMOVE_ALL',   SPEED_BUMPS_REMOVE_ALL | SPEED_BUMPS_RETURN_AND_SKIP | SPEED_BUMPS_TRUE );
```

but does that really offer any improvement?

**Comment by danielbachhuber** [comment]
No, bitmasks don't offer any improvement either. You can do a bit of googling around to get a sense of my aversion to magic numbers though.

> I've been thinking about this and still don't have a really good alternative.

What about an object / controller within the system which can carry some metadata about `can_insert`? The callback could set arbitrary metadata on the object as needed, and then the insertion logic would check the metadata before making a final determination on whether to insert.

This would also mean you don't need to internalize core code to the plugin.

**Comment by goldenapples** [comment]
Closing this PR in favor of the approach in #80

**Pull request closed without merging**
