### PR TITLE
Avoid starting variables with underscores; use public methods

### PR DESCRIPTION
**Pull request by danielbachhuber**

### CODE REVIEW

**Comment by danielbachhuber** [comment]
> is this a class with static methods, or a singleton with non-static instance methods? Up to this point all the methods have been static. Changing these to non-static instance methods might make sense, but unless we go through the whole class and standardize on one style, I think it'll get confusing for users.

@goldenapples @noppanit What's your preference? I don't have a strong opinion either way. I think the singleton pattern is nice in WordPress though to prevent actions and filters from being registered more than once.

**Comment by goldenapples** [comment]
I guess since the class registers actions, it definitely makes sense for it to be a singleton. I'm not totally able to wrap my mind around why a singleton class would have static methods, so I think I support changing the other methods here to be not static.

The Constraint classes, on the other hand, don't register any actions, so they work perfectly well as classes with static methods.

**Comment by danielbachhuber** [comment]
Sounds good.

**Comment by goldenapples** [comment]
@noppanit how do you feel about these changes? If this is merged here, you'll need to change a couple places in https://github.com/fusioneng/fusion-theme/pull/3201 where you're calling `\Speed_Bumps\Speed_Bumps::clear_all_speed_bumps();`, which will change to `Speed_Bumps()->clear_all_speed_bumps();`. 

If this looks good to you, then lets merge this and update your theme PR, and I'd call it ready to go.

**Comment by noppanit** [comment]
I think that's a lot better. So please merge it and I'll change the code.

**Pull request merged**
