### PR TITLE
Fixing test

### PR DESCRIPTION
**Pull request by noppanit**
Fixing tests related to https://github.com/fusioneng/speed-bumps/pull/12

### CODE REVIEW

**Comment by noppanit** [comment]
@goldenapples #reviewmerge please

**Comment by noppanit** [comment]
Give me 2s to fix something.

**Comment by noppanit** [comment]
@goldenapples once Travis passed please #reviewmerge

**Comment by goldenapples** [comment]
What was causing the Travis build to break before 202354e? It looks like you just removed the check to see whether $WP_TESTS_DIR existed before downloading the WP core unit test suite. Did that directory really exist on the Travis machine, or was the `No such file or directory` response being interpreted as true?

Since this file was generated by [the scaffold command in WP-CLI](https://github.com/wp-cli/wp-cli/blob/master/templates/install-wp-tests.sh), I'm wondering if we should be submitting an upstream fix there.

**Comment by noppanit** [comment]
I'm not sure what caused the error on Travis. But it looks like this repo uses different version of `install-wordpress` than any other repos that we have. So, I just updated that.

**Comment by noppanit** [comment]
I think that folder doesn't get downloaded properly on Travis machine.

**Comment by noppanit** [comment]
@goldenapples  I tracked down the issue and I tried running this command 
```
svn co http://develop.svn.wordpress.org/trunk/tests/phpunit/includes/ /tmp/wordpress-lib-tests/
```

It checks out the content to `/tmp/wordpress-lib-tests` without `includes` folder

```
A    /tmp/wordpress-lib-tests/install.php
A    /tmp/wordpress-lib-tests/wp-profiler.php
A    /tmp/wordpress-lib-tests/factory.php
A    /tmp/wordpress-lib-tests/functions.php
A    /tmp/wordpress-lib-tests/trac.php
A    /tmp/wordpress-lib-tests/testcase.php
A    /tmp/wordpress-lib-tests/testcase-ajax.php
A    /tmp/wordpress-lib-tests/bootstrap.php
A    /tmp/wordpress-lib-tests/mock-image-editor.php
A    /tmp/wordpress-lib-tests/testcase-xmlrpc.php
A    /tmp/wordpress-lib-tests/mock-fs.php
A    /tmp/wordpress-lib-tests/mock-mailer.php
A    /tmp/wordpress-lib-tests/testcase-canonical.php
A    /tmp/wordpress-lib-tests/utils.php
A    /tmp/wordpress-lib-tests/exceptions.php
```

that's why we have this error

```
require_once(/tmp/wordpress-tests-lib/includes/functions.php): failed to open stream: No such file or directory in /home/travis/build/fusioneng/speed-bumps/tests/bootstrap.php on line 8
```

**Comment by goldenapples** [comment]
Got it, thanks. Opened this issue with WP-CLI: https://github.com/wp-cli/wp-cli/issues/1885

**Comment by noppanit** [comment]
I submitted a PR https://github.com/wp-cli/wp-cli/pull/1886 to fix the issue.

**Comment by goldenapples** [comment]
OK, this looks good, and gets tests working again. I'll merge.

**Pull request merged**
