### PR TITLE
2701-speed-bumps-autoload-amend

### PR DESCRIPTION
**Pull request by anthony2727**
Push Request resubmission for [#10](https://github.com/fusioneng/speed-bumps/pull/10) against merged [#1](https://github.com/fusioneng/speed-bumps/pull/1) master. @danielbachhuber

### CODE REVIEW

**Comment by noppanit** [comment]
Thanks @anthony2727 I'm going to test this one.

**Comment by noppanit** [comment]
cc @goldenapples

**Comment by anthony2727** [comment]
Cool @noppanit . Keep me updated.

**Comment by noppanit** [comment]
@anthony2727 I have tested your PR and it looks good. Can you please merge conflict and we will merge your PR?

**Comment by anthony2727** [comment]
Absolutely @noppanit I'll give it a check and PR.

**Comment by noppanit** [comment]
Thanks a lot.

**Comment by anthony2727** [comment]
Hey @noppanit I merged the conflict with master. Let me know if it works for you. Thanks.

**Comment by noppanit** [comment]
@anthony2727 thanks a lot will do it now

**Pull request merged**
