### PR TITLE
Refactored tests and deleted unnecessary tests

### PR DESCRIPTION
**Pull request by noppanit**
@goldenapples Please have a look and let me know if this reads better. 
https://github.com/fusioneng/speed-bumps/issues/48

### CODE REVIEW

**Comment by goldenapples** [comment]
Yes, I really like the `assertSpeedBumpAtParagraph` test method. Makes the tests a lot simpler to read, and makes it easier to add new tests. If this merges, I'll rewrite some of the tests in #38 to use that method.

Do you have any thoughts on address the somewhat confusing behavior caused by zero-indexing? I notice that you're doing `$this->assertEquals( $speed_bump_paragraph, ++$actual_speed_bump_paragraph );` to kind of get around that here, so people can assert a speed bump is at paragraph 2 and it will check that it's position in the array is 1. I keep finding that issue confusing, and it would be good to shield users from that confusion where possible. 

Especially since we add another level of confusion by inserting _after_ a paragraph. So for example, the constraint functions checking whether its OK to insert a speed bump after the first paragraph would get `0` as the index passed in context. If an insertion happens at point 0, its actually after the first paragraph, and testing for it we'd be asserting that it was inserted at paragraph `2`: `$this->assertSpeedBumpAtParagraph( $content, 2, $speed_bump );`

I don't have a clear idea yet, but we must be able to protect users from this confusion with more consistant naming/indexing of things...

**Comment by noppanit** [comment]
I totally agree with that. Even I got confused a bit when I first started refactoring. I think the solution might be to be very clear from tests and codebase so when people go and read the code they would understand

**Comment by goldenapples** [comment]
I'll open a new issue for trying to clarify and simplify paragraph indexing throughout our codebase. I'd like to address that after closing some of the open pull requests. In the meantime, I think this can be merged. Are you done in this pull request?

**Comment by noppanit** [comment]
That's a good idea. Yes I'm done with the PR if you don't find anything strange please merge.

**Comment by goldenapples** [comment]
Continued discussion in #52.

**Pull request merged**
