### PR TITLE
Style cleanup

### PR DESCRIPTION
**Pull request by goldenapples**
Here's a few stylistic tweaks I thought would make this look more consistent with the rest of our projects and with WP core coding style.

- Replace all camel-cased variables with snake case
- Move the loader function to the main plugin file, add a docblock comment, and make some changes in formatting and control structures for consistency.

I think this loader could work well as part of our plugin scaffold template, so its worth taking some time to make it as clean as possible.

### CODE REVIEW

**Comment by noppanit** [comment]
Thanks a lot @goldenapples it looks good.

**Comment by noppanit** [comment]
I'm going to check it locally do you want me to merge?

**Comment by goldenapples** [comment]
Yeah, if it looks good to you, then merge it! Other than the fact that `Speed_Bumps` class isn't covered by the autoloader anymore, it doesn't change the autoloader's behavior at all or any of the existing namespaces or classes.

**Comment by anthony2727** [comment]
@goldenapples @noppanit Good improvements!

**Pull request merged**
